<?php

return array(
  'import'=>array(
    'ext.ssys.components.*',
    'ext.ssys.controllers.*',
    'ext.ssys.models.*',
  ),
  'components'=>array(
    'slog'=>array('class'=>'SsysLog'),
    'curl'=>array(
      'class'=>'CURL',
      ),
    'scenter'=>array(
       'class'=>'Scenter', 
       'baseUrl'=>'http://scenter/index.php',
       'resources'=>array(
         'app'=>array(
           'attributeNames'=>array('id','name','url','permission'),
           ),
         'answer'=>array(
           'attributeNames'=>array('id','question_id','app_id','creator_id','created_at','updated_at','typename','typedata'),
           'implAttris'=>array(
             'ValuationUnweightedGroupAnswer'=>array('minY','maxY','precision','points','bestX'),
             'MetrizableAssignmentGroupAnswer'=>array('points','maxZ','unitX','infinitX'),
             ),
           ),
         'user'=>array(
           'attributeNames'=>array('id','username','isgroup','agentname','reality'),
           ),
         'sockpuppet'=>array(
           'attributeNames'=>array('id','user_id','sockpuppetname','app_id'),
           ),
         'question'=>array(
           'attributeNames'=>array('id','app_id','questiontype','typedata','answertype','answer','created_at'),
           ),
         'integratedAnswer'=>array(
           'attributeNames'=>array("id","question_id","app_id","expectation","typename","typedata","answerset_id","updated_at"),
           ),
         'answerset'=>array(
           'attributeNames'=>array('id','app_id','selectiontype','selectioncode'),
           ),
         'userAnswer'=>array(
           'attributeNames'=>array('id','created_at','deviation','expectation','question_id','updated_at','user_id'),
           ),
         ),
     ),
    'urlManager'=>array(
      'showScriptName'=>false,
      'urlFormat'=>'path',
      'rules'=>array(
        '<controller:\w+>/<id:\d+>'=>'<controller>/view',
        '<controller:\w+>/<action:\w+>/<id:\d+>'=>'<controller>/<action>',
        '<controller:\w+>/<action:\w+>'=>'<controller>/<action>',
        '<controller:\w+>/<id:\d+>.<format:\w+>'=>'<controller>/view',
        '<controller:\w+>/<id:\d+>/<attri:\w+>.<format:\w+>'=>'<controller>/attri',
        '<controller:\w+>/<action:\w+>/<id:\d+>.<format:\w+>'=>'<controller>/<action>',
        '<controller:\w+>/<action:\w+>.<format:\w+>'=>'<controller>/<action>',
      ),
    ),
    'user'=>array(
      'class'=>'SsysWebUser',
      'allowAutoLogin'=>true,
      'loginUrl'=>array('ssys/login'),
    ),
    'oauth'=>array(
      'class'=>'Oauth',
      'config'=>array(
        /**
         * 正式服务器数据
        'qq'=>array('appId'=>'100529427',
          'appSecret'=>'f0d4ef50e392bf5b4a44af0fd9acc9c8',
          'callback'=>'user/callback',
          'scope'=>''),         
        'weibo'=>array('appId'=>'1969823864',
          'appSecret'=>'feab9f43fe37c8bb25b424cbde06e2ce',
          'callback'=>'user/callback',
          'scope'=>''
        ),
         */
        /**
         * 测试服务器数据
         */
        'qq'=>array('appId'=>'100533430',
          'appSecret'=>'2a30cc0dc37e6a6f031d445d42bcf67c',
          'callback'=>'user/callback',
          'scope'=>''),
        'weibo'=>array('appId'=>'2301706572',
          'appSecret'=>'2419c215bd42cfa880eabf8abfe4dec3',
          'callback'=>'user/callback',
          'scope'=>''
        ),        
      ),
    )
  ),
  'params'=>array(
    'duration'=>3600*24*30,// 表示记住用户登录的时间为30 days
  ),
);